#### 前言

解决 循环等待获取锁的问题而产生的。

```java
while (getCondition()) {
    
}
```

这个问题就是如果并发冲突高，可能一直获取不到执行条件，这会导致cpu一直在空转，浪费cpu资源。

如果我们第一次检测的时候，发现不满足执行条件，直接躺平（阻塞状态），等后面满足条件之后，cpu再把我拉起来就行了吧。

即**等待-通知**

> 线程获取互斥锁，当执行条件不满足时，释放互斥锁，进入等待状态，当要求的条件满足时，通知等待的线程，重新获取互斥锁。

- 等待之前是会释放互斥锁的
- 满足之后是不会立即执行的，需要等待cpu重新调度的



synchronized 会锁住一个对象，这个对象会对应一个等待队列。

这是一个Map。

- wait() 释放的是持有的互斥锁，如果有多个互斥锁，那持有的应该是所有互斥锁锁定的对象的等待队列里
- 当条件满足之后，线程会被唤醒，当被唤醒的时候，需要去获取曾经释放掉的互斥锁，可能获取不到了。



一个小插曲，我在做leetcode上面的多线程的题目，卡在了1114上，按序打印上，我的代码如下：

```java
class Foo {
        public Foo() {
        }

        volatile boolean firstDeal = false;
        volatile boolean secondDeal = false;

        public void first(Runnable printFirst) throws InterruptedException {
            synchronized (Foo.class) {
                printFirst.run();
                firstDeal = true;
                notifyAll();
            }
        }

        public void second(Runnable printSecond) throws InterruptedException {
            synchronized (Foo.class) {
                if (!firstDeal) {
                    printSecond.wait();
                }
                printSecond.run();
                notifyAll();
                secondDeal = true;
            }
        }

        public void third(Runnable printThird) throws InterruptedException {
            synchronized (Foo.class) {
                if (!secondDeal) {
                    printThird.wait();
                }
                printThird.run();
            }
        }
    }
```

当我提交执行的时候，报错了 `IllegalMonitorStateException`，我要来分析下为什么出错，以及如何改对。

线程持有的是Foo.class对象，wait调用的却是另一个对象。修改为Foo.class.wait()和notify之后，不在报错了。

```java
class Foo {
        public Foo() {
        }

        volatile boolean firstDeal = false;
        volatile boolean secondDeal = false;

        public void first(Runnable printFirst) throws InterruptedException {
            synchronized (Foo.class) {
                printFirst.run();
                firstDeal = true;
                Foo.class.notifyAll();
            }
        }

        public void second(Runnable printSecond) throws InterruptedException {
            synchronized (Foo.class) {
                if (!firstDeal) {
                    Foo.class.wait();
                } else {
                    printSecond.run();
                    secondDeal = true;
                    Foo.class.notifyAll();
                }

            }
        }

        public void third(Runnable printThird) throws InterruptedException {
            synchronized (Foo.class) {
                if (!secondDeal) {
                    Foo.class.wait();
                } else {
                    printThird.run();
                }

            }
        }
    }
```

改成这样之后，又超时了。

wait 不是从方法的最开始开始执行，而是从上次执行的地方接着执行。

成了。



```java
public class WaitTest {

    public static void main(String[] args) throws InterruptedException{
        WaitTest waitTest =  new WaitTest();
        waitTest.testWait();
        Thread.sleep(2000);
        waitTest.tt();
    }


    public void tt ()  throws InterruptedException{
        synchronized (WaitTest.class) {
            WaitTest.class.notifyAll();
        }
    }

    public void testWait()throws InterruptedException{
        synchronized (WaitTest.class) {
            System.out.println(1);
            System.out.println(2);
            System.out.println(3);
            System.out.println(4);
            System.out.println("i am wait!");
            WaitTest.class.wait();
            System.out.println("i am notify");
            System.out.println(5);
            System.out.println(6);

        }
    }

}
```

我想用上面的代码验证wait之后，是接着wait之前接着执行的，但是陷入了无限的等待。

实际上根本没办法走到tt()方法。

因为我这个是在一个线程中，这个线程被阻塞了。

所以得用线程调用。

```java
package thread;

/**
 * @author Nannf
 * @date 2021/6/21 17:47
 * @description 主要是验证wait结束之后是从方法的最开始开始执行，还是从wait之后开始执行。
 * 其实从方法的最开始执行比较扯
 * 因为我程序只是把自己挂起，不存在指令跳转命令。
 *
 * 我们要如何验证呢？
 *
 */
public class WaitTest {

    public static void main(String[] args) throws InterruptedException{
        WaitTest waitTest =  new WaitTest();
        new Thread(() -> testWait()).start();
        Thread.sleep(2000);
       new Thread(() ->tt() ).start();
    }


    public static void tt () {
        try {
            synchronized (WaitTest.class) {
                WaitTest.class.notifyAll();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void testWait(){
        try {
            synchronized (WaitTest.class) {
                System.out.println(1);
                System.out.println(2);
                System.out.println(3);
                System.out.println(4);
                System.out.println("i am wait!");
                WaitTest.class.wait();
                System.out.println("i am notify");
                System.out.println(5);
                System.out.println(6);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}

```

```text
1
2
3
4
i am wait!
i am notify
5
6
```

这是结果。说明了wait被唤醒后是在被唤醒之前的地方接着执行的。







